### ISSUE TITLE
Meta being read as a number

### ISSUE THREAD

**Issue by priyanka-surana** [priyanka-surana/readmapping#1]
### Description of the bug

Somewhere `meta` is causing this error, but I cannot find the source.
```
Cannot cast object '{id=sample1_T2, datatype=hic}' with class 'java.util.LinkedHashMap' to class 'int'
```

You can read the initial discussion on [Nf-core Slack](https://nfcore.slack.com/archives/CE6SDBX2A/p1646751188206249) and later on [Nextflow Slack](https://nextflow.slack.com/archives/C02T98A23U7/p1646823935428879).

### Relevant files

[nextflow.log](https://github.com/priyanka-surana/readmapping/files/8213148/nextflow.log)

### System information

Nextflow: 21.10.6.5660
Hardware: HPC
Executor: LSF
Container: Singularity
OS: 18.04.1-Ubuntu
Pipeline: 0.1

**Comment by mahesh-panchal** [comment]
Your log shows this exception ( but not the error above strangely ):
```
Mar-08 13:37:08.077 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: meta for class: Script_401b8f1e
Mar-08 13:37:08.113 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: No such property: meta for class: Script_401b8f1e
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at Script_401b8f1e.runScript(Script_401b8f1e:40)
```
No idea what the script should be though. Try asking directly on the Nextflow slack for help on debugging this. Perhaps someone there knows how to better debug this stack trace. 

Try incorporating the `dump` operator to see channel contents.
https://www.nextflow.io/docs/latest/operator.html#dump
That may also help narrow the issue location.

**Comment by mahesh-panchal** [comment]
Have you tried commenting out lines until the error disappears?

**Comment by priyanka-surana** [comment]
Yes I tried that. Whenever I comment out either the `input` or `output` `meta` line. I get an error similar to:
```
declares 0 input channel but 1 were specified
```

**Comment by mahesh-panchal** [comment]
> Whenever I comment out either the `input` or `output` `meta` line.

Which lines are you referring to? I really have no idea what you're trying. 

Also is your test profile working?
```
nextflow run main.nf -profile test,docker
```
I just get errors.

**Comment by priyanka-surana** [comment]
I have added a test case. When I run `nextflow run main.nf -profile test,singularity` it gives me the expected error. This is the current version in GitHub.
```
Cannot cast object '{id=sample1_T1, datatype=hic, readgroup='@RG\tID:40063_3#5_20000LH.cram\tPL:ILLUMINA\tSM:gfLaeSulp1'}' with class 'java.util.LinkedHashMap' to class 'int'
```

Removing this piece of [code](https://github.com/priyanka-surana/readmapping/blob/83698ebcfddee9a5758d40fcbcd6687409bd298e/subworkflows/local/align_hic.nf#L33) fixes the error: 
```
    // Collect all BWAMEM2 output by sample name
    BWAMEM2_MEM.out.bam
    .map { meta, bam -> meta.id = meta.id.split('_')[0..-2].join('_')[ meta, bam ] }
    .groupTuple(by: [0])
    .set { ch_bams }
```

I was trying to group all the output `bam` files by sample ID. I got the code idea from [nf-core/rnaseq workflow](https://github.com/nf-core/rnaseq/blob/7106bd792b3fb04f9f09b4e737165fa4e736ea81/workflows/rnaseq.nf#L183).

The subworkflow [`input_check`](https://github.com/priyanka-surana/readmapping/blob/main/subworkflows/local/input_check.nf) creates `meta [ sample, datatype, readgroup ]`

It is possible to have the following `input_check` output:
```
[ [ sample1_T1, hic, '@RG...' ], [ file1.cram ] ]
[ [ sample1_T2, hic, '@RG...' ], [ file2.cram ] ]
[ [ sample1_T3, hic, '@RG...' ], [ file3.cram ] ]
[ [ sample2_T1, PacBio, '@RG...' ], [ file4.bam ] ]
```

In the code above, I was trying to combine all the `sample1` files together.

**Comment by mahesh-panchal** [comment]
Ah, there's the bug where you're trying to use `meta` as an `int`.
```
    .map { meta, bam -> meta.id = meta.id.split('_')[0..-2].join('_')[ meta, bam ] }
                                                                       ^
```
I'm assuming you want to return the array `[ meta, bam]` and not index the array from `join`.
```
.map { meta, bam ->
    meta.id = meta.id.split('_')[0..-2].join('_')
    [ meta, bam ] 
}
```

**Comment by priyanka-surana** [comment]
To me the only difference between the two code snippets is newline character `/n`. What is the difference in operation, can you explain? I just want to understand for future cases.

**Comment by mahesh-panchal** [comment]
> To me the only difference between the two code snippets is newline character `/n`. What is the difference in operation, can you explain? I just want to understand for future cases.

This should explain.
https://groovy-lang.org/style-guide.html

Semi colons are optional to end a statement, and return statements are optional too.

**Comment by mahesh-panchal** [comment]
> It is still not doing what I expect it to do.
> 
> Input
> 
> ```
> [[id:sample1_T1, datatype:hic, readgroup:'@RG\tID:40063_3#5_20000LH.cram\tPL:ILLUMINA\tSM:gfLaeSulp1'], /lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/nf-core-readmapping_v2/work/81/9519638e7381ac7c88bbb71fdc915a/sample1_T1.bam]
> [[id:sample1_T2, datatype:hic, readgroup:'@RG\tID:40063_3#5_20000LH_copy.cram\tPL:ILLUMINA\tSM:gfLaeSulp1'], /lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/nf-core-readmapping_v2/work/36/6bfef8db0c4a870ea7cbb9e14d7279/sample1_T2.bam]
> ```
> 
> Current output
> 
> ```
> [[id:sample1, datatype:hic, readgroup:'@RG\tID:40063_3#5_20000LH.cram\tPL:ILLUMINA\tSM:gfLaeSulp1'], [/lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/nf-core-readmapping_v2/work/81/9519638e7381ac7c88bbb71fdc915a/sample1_T1.bam]
> [[id:sample1, datatype:hic, readgroup:'@RG\tID:40063_3#5_20000LH_copy.cram\tPL:ILLUMINA\tSM:gfLaeSulp1'], [/lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/nf-core-readmapping_v2/work/36/6bfef8db0c4a870ea7cbb9e14d7279/sample1_T2.bam]]
> ```
> 
> Expected output
> 
> ```
> [[id:sample1, datatype:hic], [/lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/nf-core-readmapping_v2/work/81/9519638e7381ac7c88bbb71fdc915a/sample1_T1.bam, /lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/nf-core-readmapping_v2/work/36/6bfef8db0c4a870ea7cbb9e14d7279/sample1_T2.bam]
> ```
> 
> Current Code:
> 
> ```
>     BWAMEM2_MEM.out.bam
>     .map { meta, bam ->
>     meta.id = meta.id.split('_')[0..-2].join('_')
>     [ meta, bam ] 
>     }   
>     .groupTuple(by: [0])
>     .set { ch_bams }
> ```

Your code here isn't doing what you expect because you're grouping on the entire object `meta`, and the `meta.readgroup`'s are not identical, hence they're not grouped as you want.

```
readgroup:'@RG\tID:40063_3#5_20000LH.cram\tPL:ILLUMINA\tSM:gfLaeSulp1'
readgroup:'@RG\tID:40063_3#5_20000LH_copy.cram\tPL:ILLUMINA\tSM:gfLaeSulp1'
```
Make those the same, and you should get what you want.

**Comment by priyanka-surana** [comment]
The `meta.readgroup` is different because it is used to add `@RG` tag to aligned BAM files. In a later step when the BAM files are merged and `samtools markdup` is run, the different readgroup value for each file is important. 

I have already used `meta.readgroup` by this step, I am look for ways to drop `meta.readgroup` at this point, then `meta` would be identical for both files. Does that make sense?

This code creates the structure I want but I lose the property `id`. I need to improve this to retain the properties `id` and `datatype`.
```nextflow
BWAMEM2_MEM.out.bam
    .map { meta, bam ->
    meta.id = meta.id.split('_')[0..-2].join('_')
    [ [meta.id, meta.datatype] , bam ]            
    }
    .groupTuple(by: [0])
    .set { ch_bams }
```

Output:
```
[[sample1, hic], [/lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/nf-core-readmapping_v2/work/97/5a246660aaba142acc943cefc501c9/sample1_T1.bam, /lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/nf-core-readmapping_v2/work/24/f1cce0b0a367aba9988ca15fcc01a3/sample1_T2.bam]]
```

Error:
```
No such variable: Exception evaluating property 'id' for java.util.ArrayList, Reason: groovy.lang.MissingPropertyException: No such property: id for class: java.lang.String
```

**Comment by mahesh-panchal** [comment]
The way I would tackle this is to use a new key so
```
meta.sample = meta.id.split('_')[0..-2].join('_')
```
That preserves `id` and let's you use `sample` e.g. for a prefix `ext.prefix = { meta.sample }`
It also means you could use that as a grouping key instead of `meta`
```
.map { meta, bam ->
    stuff
    [ meta.sample, meta, bam ]
```

Your code above also is creating an array, and not a map.
```
[ [meta.id, meta.datatype] , bam ]
```
You want
```
[ [ id: meta.id, datatype: meta.datatype ], bam ]
```

**Comment by priyanka-surana** [comment]
I went ahead with `[ [ id: meta.id, datatype: meta.datatype ], bam ]` and the workflow ran as expected.

Thank you 🙏 😊
